**Numpy Dizi İşlemleri**

In [6]:
import numpy as np #numpy kütüphanesini np takma adı ile projeye dahil ediyoruz

In [7]:
dizi=np.full((4,3),5) 
dizi 

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [8]:
#yeni bir numpy dizisi oluşturuyoruz
np.array([1,2,3])

array([1, 2, 3])

In [9]:
#oluşturduğumuz diziyi bir değişkene aktarıyoruz
dizi=np.array(["elma","erik","iğde"])

In [12]:
dizi

array([1.  , 2.  , 3.14])

In [ ]:
dizi=np.array([1,2,3])

In [11]:
dizi=np.array([1,2,3.14])

In [13]:
dizi.dtype #dizinin değişken türünü verir.

dtype('float64')

In [15]:
dizi=np.array([1,2,3.14],dtype=int)

**Numpy ile farklı boyutlarda dizi oluşturma**

In [16]:
#bir boyutlu dizi ouşturma
birboyut=np.array([1,2,3,4])
#iki boyutlu bir dizi oluşturma
ikiboyut=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [17]:
birboyut

array([1, 2, 3, 4])

In [18]:
ikiboyut

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**Numpy yer tutucular**

In [19]:
np.zeros(7) #7 sıfırdan oluşan tek dizi oluşturur

array([0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.zeros((2,3),dtype=int) #sıfırdan oluşan 2 boyutlu int dizisi oluşturur

array([[0, 0, 0],
       [0, 0, 0]])

In [23]:
np.ones(3)

array([1., 1., 1.])

In [24]:
np.full((4,3),5) #5 sayısından oluşan 2*3 lük dizi

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [25]:
np.arange(2,22,5) #başlangıç,bitiş ve artış değerine göre diz oluşturma

array([ 2,  7, 12, 17])

In [26]:
np.linspace(2,10,num=7) #başlangıç ve bitiş değeri aralığında belirtilen miktarda eşit aralık

array([ 2.        ,  3.33333333,  4.66666667,  6.        ,  7.33333333,
        8.66666667, 10.        ])

In [27]:
np.random.randint(0,10,(5,2)) #0-10 aralığında 5*2 rasgele sayıdan oluşan 2 boyutlu dizi

array([[8, 7],
       [7, 7],
       [3, 5],
       [4, 8],
       [3, 5]])

**Diziler ile ilgili işlemler**

In [28]:
#dizilerin eleman sayısını öğrenmek için shope komutu kullanılır
dizi=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
dizi.shape

(3, 4)

In [29]:
#ndim dizi boyutu öğrenmek için kullanır
dizi.ndim

2

In [30]:
#size dizideki toplam eleman sayısnı gösterir
dizi.size

12

In [31]:
dizi.itemsize #dizideki her bir elemanın bayt cinsinden değerini verir

4